on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

name: Render with the subset data

permissions:
  contents: write
  pull-requests: write

jobs:
  render:
    runs-on: 'ubuntu-latest'
    concurrency:
      group: render-subset-data-${{ github.event.number }}
    name: Render the book using the small dataset
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to GH pages preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/